site:
  title: Yogurt Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://yocurt.github.com/docs
  start_page: yogurt::index.adoc
content:
  sources:
  - url: https://github.com/yocurt/yogurt.git
    branches: master
    start_path: docs
ui:
  bundle:
    url: https://github.com/anoff/antora-arc42-ui/releases/download/1.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
