site:
  title: Yogurt Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://yocurt.github.com/docs
  start_page: yogurt::index.adoc
content:
  sources:
  - url: ./yogurt
    branches: master
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
