name: Create Antora Site & Publish to Github Pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: git clone https://github.com/yocurt/yogurt.git yogurt
    - name: Generate Site
      uses: jsqu4re/antora_build@0.1.1
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN_PAGES }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build/site
      
